In [1]:
import numpy as np  # NumPy kitabxanasını import edirik
import pandas as pd  # Pandas kitabxanasını import edirik
import random  # Təsadüfi seçim üçün random modulunu import edirik

cohort = ["alpha", "beta", "gamma"]  # Cohort siyahısı yaradırıq

attendance_raw = []  # Tələbə məlumatlarını saxlamaq üçün boş siyahı

for i in range(1,25):  # 1-dən 24-ə qədər tələbələr üçün dövr
    attendance_1 = {
            "student_id": f"S{i:03}",  # S001 formatında tələbə ID
            "cohort": random.choice(cohort),  # Təsadüfi cohort seçimi
            "attended_sessions": random.randint(0,6),  # 0-6 arası təsadüfi iştirak sayı
            "expected_sessions": 6  # Gözlənilən dərs sayı sabit 6
    }
    attendance_raw.append(attendance_1)  # Məlumatı siyahıya əlavə edirik

attendance_raw  # Nəticəni göstəririk

[{'student_id': 'S001',
  'cohort': 'gamma',
  'attended_sessions': 4,
  'expected_sessions': 6},
 {'student_id': 'S002',
  'cohort': 'beta',
  'attended_sessions': 0,
  'expected_sessions': 6},
 {'student_id': 'S003',
  'cohort': 'alpha',
  'attended_sessions': 0,
  'expected_sessions': 6},
 {'student_id': 'S004',
  'cohort': 'gamma',
  'attended_sessions': 2,
  'expected_sessions': 6},
 {'student_id': 'S005',
  'cohort': 'beta',
  'attended_sessions': 1,
  'expected_sessions': 6},
 {'student_id': 'S006',
  'cohort': 'gamma',
  'attended_sessions': 2,
  'expected_sessions': 6},
 {'student_id': 'S007',
  'cohort': 'gamma',
  'attended_sessions': 5,
  'expected_sessions': 6},
 {'student_id': 'S008',
  'cohort': 'beta',
  'attended_sessions': 3,
  'expected_sessions': 6},
 {'student_id': 'S009',
  'cohort': 'beta',
  'attended_sessions': 3,
  'expected_sessions': 6},
 {'student_id': 'S010',
  'cohort': 'gamma',
  'attended_sessions': 2,
  'expected_sessions': 6},
 {'student_id': 'S011',
  'cohort': 'beta',
  'attended_sessions': 3,
  'expected_sessions': 6},
 {'student_id': 'S012',
  'cohort': 'beta',
  'attended_sessions': 2,
  'expected_sessions': 6},
 {'student_id': 'S013',
  'cohort': 'gamma',
  'attended_sessions': 4,
  'expected_sessions': 6},
 {'student_id': 'S014',
  'cohort': 'beta',
  'attended_sessions': 6,
  'expected_sessions': 6},
 {'student_id': 'S015',
  'cohort': 'beta',
  'attended_sessions': 3,
  'expected_sessions': 6},
 {'student_id': 'S016',
  'cohort': 'beta',
  'attended_sessions': 6,
  'expected_sessions': 6},
 {'student_id': 'S017',
  'cohort': 'alpha',
  'attended_sessions': 5,
  'expected_sessions': 6},
 {'student_id': 'S018',
  'cohort': 'gamma',
  'attended_sessions': 5,
  'expected_sessions': 6},
 {'student_id': 'S019',
  'cohort': 'beta',
  'attended_sessions': 6,
  'expected_sessions': 6},
 {'student_id': 'S020',
  'cohort': 'beta',
  'attended_sessions': 4,
  'expected_sessions': 6},
 {'student_id': 'S021',
  'cohort': 'beta',
  'attended_sessions': 1,
  'expected_sessions': 6},
 {'student_id': 'S022',
  'cohort': 'beta',
  'attended_sessions': 3,
  'expected_sessions': 6},
 {'student_id': 'S023',
  'cohort': 'gamma',
  'attended_sessions': 4,
  'expected_sessions': 6},
 {'student_id': 'S024',
  'cohort': 'gamma',
  'attended_sessions': 6,
  'expected_sessions': 6}]

In [2]:
attendance = pd.DataFrame(attendance_raw)
attendance[:5]

  student_id cohort  attended_sessions  expected_sessions
0       S001  gamma                  4                  6
1       S002   beta                  0                  6
2       S003  alpha                  0                  6
3       S004  gamma                  2                  6
4       S005   beta                  1                  6

In [3]:
# "student_id" sütununu indeks kimi təyin edirik
# İlk 5 sətri göstəririk
attendance_indexed = attendance.set_index("student_id")
attendance_indexed[:5]

           cohort  attended_sessions  expected_sessions
student_id
S001        gamma                  4                  6
S002         beta                  0                  6
S003        alpha                  0                  6
S004        gamma                  2                  6
S005         beta                  1                  6

In [4]:
# Müxtəlif tələbələr üçün icazəli absensiyaları Series olaraq yaradılır
# Series-in indeksi tələbə ID-ləridir, dəyərlər isə absensiya sayını göstərir
excused_absences = pd.Series(
    [1,2,3,4,5,6,7,8,9,10],
    index=["S003","S005","S017","S025","S026","S027","S028","S029","S030","S031"]
)
excused_absences

S003     1
S005     2
S017     3
S025     4
S026     5
S027     6
S028     7
S029     8
S030     9
S031    10
dtype: int64

In [5]:
# Tələbələrin həqiqi iştirakını tənzimləmək üçün "attended_sessions" və "excused_absences" toplandı
# Yeni sütun "adjusted_attendance" yaradılır
attendance_indexed["adjusted_attendance"] = attendance_indexed["attended_sessions"] + excused_absences
attendance_indexed

           cohort  attended_sessions  expected_sessions  adjusted_attendance
student_id
S001        gamma                  4                  6                  NaN
S002         beta                  0                  6                  NaN
S003        alpha                  0                  6                  1.0
S004        gamma                  2                  6                  NaN
S005         beta                  1                  6                  3.0
S006        gamma                  2                  6                  NaN
S007        gamma                  5                  6                  NaN
S008         beta                  3                  6                  NaN
S009         beta                  3                  6                  NaN
S010        gamma                  2                  6                  NaN
S011         beta                  3                  6                  NaN
S012         beta                  2                  6                  NaN
S013        gamma                  4                  6                  NaN
S014         beta                  6                  6                  NaN
S015         beta                  3                  6                  NaN
S016         beta                  6                  6                  NaN
S017        alpha                  5                  6                  8.0
S018        gamma                  5                  6                  NaN
S019         beta                  6                  6                  NaN
S020         beta                  4                  6                  NaN
S021         beta                  1                  6                  NaN
S022         beta                  3                  6                  NaN
S023        gamma                  4                  6                  NaN
S024        gamma                  6                  6                  NaN

In [6]:
# "adjusted_attendance" sütununda NaN dəyərləri yoxlanılır
attendance_indexed["adjusted_attendance"].isna()

# NaN dəyərlərini orijinal "attended_sessions" dəyərləri ilə doldururuq
attendance_indexed["adjusted_attendance"] = attendance_indexed["adjusted_attendance"].fillna(attendance_indexed["attended_sessions"])

# Yenilənmiş "adjusted_attendance" sütunu göstərilir
attendance_indexed["adjusted_attendance"]

student_id
S001    4.0
S002    0.0
S003    1.0
S004    2.0
S005    3.0
S006    2.0
S007    5.0
S008    3.0
S009    3.0
S010    2.0
S011    3.0
S012    2.0
S013    4.0
S014    6.0
S015    3.0
S016    6.0
S017    8.0
S018    5.0
S019    6.0
S020    4.0
S021    1.0
S022    3.0
S023    4.0
S024    6.0
Name: adjusted_attendance, dtype: float64

In [7]:
attendance_indexed.loc["S003","cohort"] = "BETA "
attendance_indexed.loc["S007","cohort"] = "GAMMA"
attendance_indexed.loc["S009","cohort"] = " gamma "
attendance_indexed.loc["S013","cohort"] = "beta "
attendance_indexed.loc["S024","cohort"] = "gamma"
attendance_indexed

             cohort  attended_sessions  expected_sessions  adjusted_attendance
student_id
S001          gamma                  4                  6                  4.0
S002           beta                  0                  6                  0.0
S003          BETA                   0                  6                  1.0
S004          gamma                  2                  6                  2.0
S005           beta                  1                  6                  3.0
S006          gamma                  2                  6                  2.0
S007          GAMMA                  5                  6                  5.0
S008           beta                  3                  6                  3.0
S009         gamma                   3                  6                  3.0
S010          gamma                  2                  6                  2.0
S011           beta                  3                  6                  3.0
S012           beta                  2                  6                  2.0
S013          beta                   4                  6                  4.0
S014           beta                  6                  6                  6.0
S015           beta                  3                  6                  3.0
S016           beta                  6                  6                  6.0
S017          alpha                  5                  6                  8.0
S018          gamma                  5                  6                  5.0
S019           beta                  6                  6                  6.0
S020           beta                  4                  6                  4.0
S021           beta                  1                  6                  1.0
S022           beta                  3                  6                  3.0
S023          gamma                  4                  6                  4.0
S024          gamma                  6                  6                  6.0

In [8]:
attendance_indexed["cohort"] = attendance_indexed["cohort"].str.lower().str.strip()
attendance_indexed

           cohort  attended_sessions  expected_sessions  adjusted_attendance
student_id
S001        gamma                  4                  6                  4.0
S002         beta                  0                  6                  0.0
S003         beta                  0                  6                  1.0
S004        gamma                  2                  6                  2.0
S005         beta                  1                  6                  3.0
S006        gamma                  2                  6                  2.0
S007        gamma                  5                  6                  5.0
S008         beta                  3                  6                  3.0
S009        gamma                  3                  6                  3.0
S010        gamma                  2                  6                  2.0
S011         beta                  3                  6                  3.0
S012         beta                  2                  6                  2.0
S013         beta                  4                  6                  4.0
S014         beta                  6                  6                  6.0
S015         beta                  3                  6                  3.0
S016         beta                  6                  6                  6.0
S017        alpha                  5                  6                  8.0
S018        gamma                  5                  6                  5.0
S019         beta                  6                  6                  6.0
S020         beta                  4                  6                  4.0
S021         beta                  1                  6                  1.0
S022         beta                  3                  6                  3.0
S023        gamma                  4                  6                  4.0
S024        gamma                  6                  6                  6.0

In [10]:
attendance_indexed["cohort"].unique()

array(['gamma', 'beta', 'alpha'], dtype=object)

In [11]:
# "attended_sessions" sütunu "expected_sessions" dəyərindən az olan tələbələri seçirik
low_attendance = attendance_indexed[attendance_indexed["attended_sessions"] < attendance_indexed["expected_sessions"]]

# İlk 2 sətri göstəririk
low_attendance[:2]

           cohort  attended_sessions  expected_sessions  adjusted_attendance
student_id
S001        gamma                  4                  6                  4.0
S002         beta                  0                  6                  0.0

In [12]:
summary = low_attendance.groupby("cohort")["attended_sessions"].mean()
summary

cohort
alpha    5.000000
beta     2.181818
gamma    3.375000
Name: attended_sessions, dtype: float64

In [17]:
attendance_indexed["attendance_ok"]=attendance_indexed["attended_sessions"]>=attendance_indexed["expected_sessions"]
attendance_indexed

,cohort,attended_sessions,expected_sessions,adjusted_attendance,attendance_ok
student_id,,,,,
S001,gamma,4,6,4.0,False
S002,beta,0,6,0.0,False
S003,beta,0,6,1.0,False
S004,gamma,2,6,2.0,False
S005,beta,1,6,3.0,False
S006,gamma,2,6,2.0,False
S007,gamma,5,6,5.0,False
S008,beta,3,6,3.0,False
S009,gamma,3,6,3.0,False
S010,gamma,2,6,2.0,False
S011,beta,3,6,3.0,False
S012,beta,2,6,2.0,False
S013,beta,4,6,4.0,False
S014,beta,6,6,6.0,True
S015,beta,3,6,3.0,False
S016,beta,6,6,6.0,True
S017,alpha,5,6,8.0,False
S018,gamma,5,6,5.0,False
S019,beta,6,6,6.0,True
S020,beta,4,6,4.0,False
S021,beta,1,6,1.0,False
S022,beta,3,6,3.0,False
S023,gamma,4,6,4.0,False
S024,gamma,6,6,6.0,True

In [20]:
#(low_attendance["attendance_ok"] == False)  bu error verdi ona gore de

low_attendance_ok_check = attendance_indexed[attendance_indexed["attended_sessions"] < attendance_indexed["expected_sessions"]]["attendance_ok"] == False
low_attendance_ok_check

student_id
S001    True
S002    True
S003    True
S004    True
S005    True
S006    True
S007    True
S008    True
S009    True
S010    True
S011    True
S012    True
S013    True
S015    True
S017    True
S018    True
S020    True
S021    True
S022    True
S023    True
Name: attendance_ok, dtype: bool